name: test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-slim
    container:
      image: busybox:musl
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: hush test/run.sh
