name: test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests in busybox
        run: docker run --rm -v $PWD:/test busybox:musl hush /test/test/run.sh
